export{ default as enlaceBackground} from './enlacebackground.png'
export{ default as enlaceLogo } from './enlacelogo.svg'
export{ default as jumanjiBackground} from './jumanjiBackground.png'
export{ default as jumanjiLogo } from './jumanjiLogo.png'
export{ default as wheelBackground } from './wheelBackground.png'
export{ default as wheelLogo} from './wheelLogo.png'
export{ default as recetteBackground} from './recetteBackground.png'
export{ default as recetteLogo} from './recetteLogo.svg'